# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addPassWindow(object):
    def setupUi(self, addPassWindow):
        addPassWindow.setObjectName("addPassWindow")
        addPassWindow.resize(598, 425)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addPassWindow.setWindowIcon(icon)
        addPassWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(addPassWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.memoDateBox = QtWidgets.QDateEdit(self.centralwidget)
        self.memoDateBox.setGeometry(QtCore.QRect(360, 90, 121, 31))
        self.memoDateBox.setObjectName("memoDateBox")
        self.passDateBox = QtWidgets.QDateEdit(self.centralwidget)
        self.passDateBox.setGeometry(QtCore.QRect(390, 260, 91, 31))
        self.passDateBox.setObjectName("passDateBox")
        self.isSingleBox = QtWidgets.QCheckBox(self.centralwidget)
        self.isSingleBox.setGeometry(QtCore.QRect(490, 260, 131, 17))
        self.isSingleBox.setChecked(True)
        self.isSingleBox.setObjectName("isSingleBox")
        self.passDate2Box = QtWidgets.QDateEdit(self.centralwidget)
        self.passDate2Box.setEnabled(False)
        self.passDate2Box.setGeometry(QtCore.QRect(390, 310, 91, 31))
        self.passDate2Box.setObjectName("passDate2Box")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 0, 481, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.addPassBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addPassBtn.setGeometry(QtCore.QRect(360, 360, 121, 31))
        self.addPassBtn.setObjectName("addPassBtn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 70, 151, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 140, 151, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 190, 151, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 240, 151, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(360, 140, 151, 16))
        self.label_6.setObjectName("label_6")
        self.label_from = QtWidgets.QLabel(self.centralwidget)
        self.label_from.setGeometry(QtCore.QRect(360, 270, 21, 16))
        self.label_from.setObjectName("label_from")
        self.label_to = QtWidgets.QLabel(self.centralwidget)
        self.label_to.setGeometry(QtCore.QRect(360, 310, 21, 16))
        self.label_to.setObjectName("label_to")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 120, 611, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(360, 70, 151, 16))
        self.label_9.setObjectName("label_9")
        self.memoNumBox = QtWidgets.QLineEdit(self.centralwidget)
        self.memoNumBox.setGeometry(QtCore.QRect(100, 90, 151, 31))
        self.memoNumBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.memoNumBox.setInputMask("")
        self.memoNumBox.setText("")
        self.memoNumBox.setMaxLength(32772)
        self.memoNumBox.setCursorPosition(0)
        self.memoNumBox.setPlaceholderText("")
        self.memoNumBox.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.memoNumBox.setClearButtonEnabled(False)
        self.memoNumBox.setObjectName("memoNumBox")
        self.surnameBox = QtWidgets.QLineEdit(self.centralwidget)
        self.surnameBox.setGeometry(QtCore.QRect(100, 160, 151, 31))
        self.surnameBox.setInputMask("")
        self.surnameBox.setObjectName("surnameBox")
        self.nameBox = QtWidgets.QLineEdit(self.centralwidget)
        self.nameBox.setGeometry(QtCore.QRect(100, 210, 151, 31))
        self.nameBox.setObjectName("nameBox")
        self.fathernameBox = QtWidgets.QLineEdit(self.centralwidget)
        self.fathernameBox.setGeometry(QtCore.QRect(100, 260, 151, 31))
        self.fathernameBox.setObjectName("fathernameBox")
        self.carnumBox = QtWidgets.QLineEdit(self.centralwidget)
        self.carnumBox.setGeometry(QtCore.QRect(360, 160, 121, 31))
        self.carnumBox.setInputMask("")
        self.carnumBox.setText("")
        self.carnumBox.setObjectName("carnumBox")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(360, 190, 151, 16))
        self.label_7.setObjectName("label_7")
        self.autoBrandBox = QtWidgets.QLineEdit(self.centralwidget)
        self.autoBrandBox.setGeometry(QtCore.QRect(360, 210, 121, 31))
        self.autoBrandBox.setInputMask("")
        self.autoBrandBox.setText("")
        self.autoBrandBox.setObjectName("autoBrandBox")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(100, 360, 151, 16))
        self.label_8.setObjectName("label_8")
        addPassWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(addPassWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 598, 21))
        self.menubar.setObjectName("menubar")
        addPassWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(addPassWindow)
        self.statusbar.setObjectName("statusbar")
        addPassWindow.setStatusBar(self.statusbar)

        self.retranslateUi(addPassWindow)
        QtCore.QMetaObject.connectSlotsByName(addPassWindow)

    def retranslateUi(self, addPassWindow):
        _translate = QtCore.QCoreApplication.translate
        addPassWindow.setWindowTitle(_translate("addPassWindow", "Добавить пропуск"))
        self.isSingleBox.setText(_translate("addPassWindow", "Одноразовый"))
        self.label.setText(_translate("addPassWindow", "Новый пропуск"))
        self.addPassBtn.setText(_translate("addPassWindow", "Добавить пропуск"))
        self.label_2.setText(_translate("addPassWindow", "Номер служебной записки"))
        self.label_3.setText(_translate("addPassWindow", "Фамилия водителя*"))
        self.label_4.setText(_translate("addPassWindow", "Имя водителя*"))
        self.label_5.setText(_translate("addPassWindow", "Отчество водителя*"))
        self.label_6.setText(_translate("addPassWindow", "Номер автомобиля*"))
        self.label_from.setText(_translate("addPassWindow", "От*"))
        self.label_to.setText(_translate("addPassWindow", "До"))
        self.label_9.setText(_translate("addPassWindow", "Дата служебной записки*"))
        self.carnumBox.setPlaceholderText(_translate("addPassWindow", " А123БВ"))
        self.label_7.setText(_translate("addPassWindow", "Марка автомобиля"))
        self.autoBrandBox.setPlaceholderText(_translate("addPassWindow", "Honda"))
        self.label_8.setText(_translate("addPassWindow", "* - обязательные поля"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addPassWindow = QtWidgets.QMainWindow()
    ui = Ui_addPassWindow()
    ui.setupUi(addPassWindow)
    addPassWindow.show()
    sys.exit(app.exec_())
